name: Deploy to Codeberg Pages

on:
  push:
    branches:
      - main

jobs:
  build-site:
    runs-on: codeberg-small
    steps:
      - uses: actions/checkout@v7
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.9
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"
      - name: Install pipenv
        run: pip install pipenv
      - name: Install dependencies
        run: pipenv install
      - name: Render site
        run: pipenv run quarto render

  deploy-production:
    needs: build-site
    runs-on: codeberg-small
    steps:
      - uses: actions/git-pages@v2
        with:
          site: https://tue-datastewards.codeberg.page/rdm-dash/
          token: ${{ forgejo.token }}
          source: _site/