name: PR Preview Deployment

on:
  pull_request:
    types:
      - opened
      - synchronize
      - closed

permissions:
  contents: write
  pull-requests: write

concurrency: preview-${{ github.ref }}

jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: release
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"
      - name: Install pipenv
        run: pip install pipenv
      - name: Install dependencies
        run: pipenv install
      - name: Render site
        run: pipenv run quarto render
      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: _site/
